import { Activity as ActivityIcon, BarChart3, Check, Clock3, Filter, LayoutDashboard, LogOut, Menu, Settings, Workflow, X, Zap, AlertCircle } from "lucide-react";
import { useMemo, useState } from "react";

const items = [
  ["Lead qualificado","CRM → Pipeline","2 min atrás","success"],["Relatório gerado","Analytics → PDF","8 min atrás","success"],["Email enviado","Marketing → Cliente","12 min atrás","success"],["Workflow iniciado","Lead qualification","18 min atrás","running"],["CRM atualizado","NEXA → HubSpot","24 min atrás","success"],["Follow-up aguardando","Marketing → Email","31 min atrás","waiting"],["Workflow falhou","Webhook → CRM","43 min atrás","failed"],["Dados sincronizados","ERP → Analytics","1 h atrás","success"],
] as const;
type Status = "all" | "success" | "running" | "waiting" | "failed";

function Activity() {
 const [sidebarOpen,setSidebarOpen]=useState(false); const [filter,setFilter]=useState<Status>("all");
 const filtered=useMemo(()=>filter==="all"?items:items.filter(x=>x[3]===filter),[filter]);
 const nav=[["Overview",LayoutDashboard,"/dashboard"],["Workflows",Workflow,"/dashboard/workflows"],["Analytics",BarChart3,"/dashboard/analytics"],["Activity",ActivityIcon,"/dashboard/activity"]] as const;
 return <main className="min-h-screen bg-[#050505] text-white"><div className="flex min-h-screen">
 <aside className={`fixed inset-y-0 left-0 z-50 w-64 border-r border-white/7 bg-[#080808] p-5 transition-transform duration-300 lg:static lg:translate-x-0 ${sidebarOpen?"translate-x-0":"-translate-x-full"}`}><div className="flex h-full flex-col"><div className="flex items-center justify-between"><a href="/" className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl border border-white/10 bg-white/[0.06] text-sm font-semibold">N</span><span className="text-sm font-semibold">NEXA</span></a><button onClick={()=>setSidebarOpen(false)} className="p-2 text-white/45 lg:hidden"><X className="h-4 w-4"/></button></div><nav className="mt-10 space-y-1">{nav.map(([label,Icon,href])=><a key={label} href={href} className={`flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm ${label==="Activity"?"bg-white/[0.08]":"text-white/45 hover:bg-white/[0.04] hover:text-white"}`}><Icon className="h-4 w-4"/>{label}</a>)}</nav><div className="mt-auto space-y-1"><a href="/dashboard/settings" className="flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm text-white/45 hover:bg-white/[0.04] hover:text-white"><Settings className="h-4 w-4"/>Settings</a><a href="/" className="flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm text-white/45 hover:bg-white/[0.04] hover:text-white"><LogOut className="h-4 w-4"/>Voltar para o site</a></div></div></aside>
 {sidebarOpen&&<button onClick={()=>setSidebarOpen(false)} className="fixed inset-0 z-40 bg-black/60 lg:hidden"/>}
 <section className="min-w-0 flex-1"><header className="sticky top-0 z-30 flex h-16 items-center border-b border-white/7 bg-[#050505]/85 px-5 backdrop-blur-xl sm:px-8"><button onClick={()=>setSidebarOpen(true)} className="rounded-xl border border-white/8 p-2 text-white/55 lg:hidden"><Menu className="h-4 w-4"/></button><div className="hidden items-center gap-2 text-xs text-white/35 lg:flex"><ActivityIcon className="h-3.5 w-3.5"/>Workspace / Activity</div><div className="ml-auto flex items-center gap-3"><span className="hidden rounded-full border border-white/8 bg-white/[0.03] px-3 py-1.5 text-xs text-white/55 sm:block">● All systems operational</span><span className="grid h-8 w-8 place-items-center rounded-full border border-white/10 bg-white/[0.08] text-xs">LB</span></div></header>
 <div className="mx-auto max-w-[1100px] px-5 py-8 sm:px-8 lg:px-10"><div><p className="text-xs font-medium uppercase tracking-[0.2em] text-white/35">Operation log</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.04em] sm:text-4xl">Activity.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-white/45">Um histórico de tudo que a NEXA executou, iniciou ou sinalizou na sua operação.</p></div>
 <div className="mt-8 flex flex-wrap gap-2">{([["all","Todos"],["success","Sucesso"],["running","Executando"],["waiting","Aguardando"],["failed","Falhas"]] as const).map(([key,label])=><button key={key} onClick={()=>setFilter(key)} className={`rounded-full border px-3.5 py-2 text-xs transition ${filter===key?"border-white/20 bg-white text-black":"border-white/8 bg-white/[0.03] text-white/45 hover:text-white"}`}><Filter className="mr-1.5 inline h-3 w-3"/>{label}</button>)}</div>
 <section className="mt-5 overflow-hidden rounded-2xl border border-white/7 bg-white/[0.025]"><div className="grid grid-cols-[1fr_auto] border-b border-white/7 px-5 py-4 text-xs text-white/30 sm:grid-cols-[1fr_150px_130px]"><span>Event</span><span className="hidden sm:block">Status</span><span>Time</span></div>{filtered.map(([title,detail,time,status])=><div key={title+time} className="grid grid-cols-[1fr_auto] items-center gap-4 border-b border-white/6 px-5 py-4 last:border-0 sm:grid-cols-[1fr_150px_130px]"><div className="flex min-w-0 items-center gap-3"><div className={`grid h-9 w-9 shrink-0 place-items-center rounded-xl ${status==="failed"?"bg-red-400/[0.08]":status==="running"?"bg-white/[0.08]":"bg-emerald-400/[0.07]"}`}>{status==="failed"?<AlertCircle className="h-4 w-4 text-red-300/80"/>:status==="running"?<Zap className="h-4 w-4 text-white/60"/>:<Check className="h-4 w-4 text-emerald-300/80"/>}</div><div className="min-w-0"><p className="truncate text-sm font-medium">{title}</p><p className="mt-1 truncate text-xs text-white/30">{detail}</p></div></div><span className="hidden text-xs capitalize text-white/45 sm:block">{status}</span><span className="text-xs text-white/30">{time}</span></div>)}</section>
 <div className="mt-4 flex items-center gap-2 text-xs text-white/25"><Clock3 className="h-3.5 w-3.5"/>Showing {filtered.length} events from the current demo workspace.</div>
 </div></section></div></main>;
}
export default Activity;
