import { Bell, Check, ChevronRight, Globe2, LayoutDashboard, LogOut, Menu, Settings as SettingsIcon, Shield, SlidersHorizontal, Workflow, BarChart3, Activity, X } from "lucide-react";
import { useState } from "react";

function Settings() {
 const [sidebarOpen,setSidebarOpen]=useState(false); const [notifications,setNotifications]=useState(true); const [alerts,setAlerts]=useState(true); const [reports,setReports]=useState(false); const [saved,setSaved]=useState(false);
 const nav=[["Overview",LayoutDashboard,"/dashboard"],["Workflows",Workflow,"/dashboard/workflows"],["Analytics",BarChart3,"/dashboard/analytics"],["Activity",Activity,"/dashboard/activity"]] as const;
 const save=()=>{setSaved(true); window.setTimeout(()=>setSaved(false),1800)};
 return <main className="min-h-screen bg-[#050505] text-white"><div className="flex min-h-screen">
 <aside className={`fixed inset-y-0 left-0 z-50 w-64 border-r border-white/7 bg-[#080808] p-5 transition-transform duration-300 lg:static lg:translate-x-0 ${sidebarOpen?"translate-x-0":"-translate-x-full"}`}><div className="flex h-full flex-col"><div className="flex items-center justify-between"><a href="/" className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl border border-white/10 bg-white/[0.06] text-sm font-semibold">N</span><span className="text-sm font-semibold">NEXA</span></a><button onClick={()=>setSidebarOpen(false)} className="p-2 text-white/45 lg:hidden"><X className="h-4 w-4"/></button></div><nav className="mt-10 space-y-1">{nav.map(([label,Icon,href])=><a key={label} href={href} className="flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm text-white/45 hover:bg-white/[0.04] hover:text-white"><Icon className="h-4 w-4"/>{label}</a>)}</nav><div className="mt-auto space-y-1"><a href="/dashboard/settings" className="flex items-center gap-3 rounded-xl bg-white/[0.08] px-3 py-2.5 text-sm"><SettingsIcon className="h-4 w-4"/>Settings</a><a href="/" className="flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm text-white/45 hover:bg-white/[0.04] hover:text-white"><LogOut className="h-4 w-4"/>Voltar para o site</a></div></div></aside>
 {sidebarOpen&&<button onClick={()=>setSidebarOpen(false)} className="fixed inset-0 z-40 bg-black/60 lg:hidden"/>}
 <section className="min-w-0 flex-1"><header className="sticky top-0 z-30 flex h-16 items-center border-b border-white/7 bg-[#050505]/85 px-5 backdrop-blur-xl sm:px-8"><button onClick={()=>setSidebarOpen(true)} className="rounded-xl border border-white/8 p-2 text-white/55 lg:hidden"><Menu className="h-4 w-4"/></button><div className="hidden items-center gap-2 text-xs text-white/35 lg:flex"><SettingsIcon className="h-3.5 w-3.5"/>Workspace / Settings</div><div className="ml-auto grid h-8 w-8 place-items-center rounded-full border border-white/10 bg-white/[0.08] text-xs">LB</div></header>
 <div className="mx-auto max-w-[1050px] px-5 py-8 sm:px-8 lg:px-10"><div><p className="text-xs font-medium uppercase tracking-[0.2em] text-white/35">Workspace configuration</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.04em] sm:text-4xl">Settings.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-white/45">Configure o workspace e escolha como a NEXA deve acompanhar sua operação.</p></div>
 <div className="mt-8 grid gap-6 lg:grid-cols-[1fr_300px]"><div className="space-y-6">
 <section className="rounded-2xl border border-white/7 bg-white/[0.025] p-6"><div className="flex items-center gap-3"><Globe2 className="h-4 w-4 text-white/50"/><div><h2 className="text-sm font-medium">Workspace</h2><p className="text-xs text-white/30">Informações principais</p></div></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-xs text-white/35">Nome da empresa<input defaultValue="NEXA Demo Workspace" className="mt-2 w-full rounded-xl border border-white/8 bg-white/[0.03] px-3 py-3 text-sm text-white outline-none focus:border-white/20"/></label><label className="text-xs text-white/35">Email<input defaultValue="lucas@nexa.demo" className="mt-2 w-full rounded-xl border border-white/8 bg-white/[0.03] px-3 py-3 text-sm text-white outline-none focus:border-white/20"/></label></div></section>
 <section className="rounded-2xl border border-white/7 bg-white/[0.025] p-6"><div className="flex items-center gap-3"><Bell className="h-4 w-4 text-white/50"/><div><h2 className="text-sm font-medium">Notifications</h2><p className="text-xs text-white/30">Controle os avisos da operação</p></div></div><div className="mt-6 divide-y divide-white/6">{[["Notificações gerais",notifications,setNotifications],["Alertas de workflow",alerts,setAlerts],["Relatórios semanais",reports,setReports]].map(([label,value,setter])=><div key={label as string} className="flex items-center justify-between gap-4 py-4 first:pt-0 last:pb-0"><div><p className="text-sm">{label as string}</p><p className="mt-1 text-xs text-white/30">Preferência salva apenas nesta demonstração.</p></div><button type="button" onClick={()=>{(setter as (v:boolean)=>void)(!(value as boolean));setSaved(false)}} className={`relative h-6 w-11 rounded-full transition ${value?"bg-white":"bg-white/10"}`}><span className={`absolute top-1 h-4 w-4 rounded-full transition ${value?"left-6 bg-black":"left-1 bg-white/50"}`}/></button></div>)}</div></section>
 <button onClick={save} className="inline-flex items-center gap-2 rounded-full bg-white px-5 py-3 text-sm font-medium text-black">{saved?<><Check className="h-4 w-4"/>Saved</>:<>Save changes<ChevronRight className="h-4 w-4"/></>}</button>
 </div>
 <aside className="h-fit space-y-6"><section className="rounded-2xl border border-white/8 bg-white/[0.035] p-6"><div className="flex items-center gap-3"><Shield className="h-4 w-4 text-white/60"/><h2 className="text-sm font-medium">Plan</h2></div><p className="mt-5 text-2xl font-semibold">Growth</p><p className="mt-1 text-xs text-white/35">Built for growing operations</p><div className="mt-6 h-px bg-white/7"/><div className="mt-5 space-y-4 text-xs"><div className="flex justify-between"><span className="text-white/35">Workflows</span><span>∞</span></div><div className="flex justify-between"><span className="text-white/35">Executions</span><span>8.492 / 10.000</span></div><div className="flex justify-between"><span className="text-white/35">Renewal</span><span>Oct 28, 2026</span></div></div></section><section className="rounded-2xl border border-white/7 bg-white/[0.025] p-5"><div className="flex items-center gap-2 text-xs text-white/35"><SlidersHorizontal className="h-3.5 w-3.5"/>Demo environment</div><p className="mt-3 text-xs leading-5 text-white/30">Estas configurações simulam uma experiência de produto. Nenhum dado é enviado para um serviço externo.</p></section></aside>
 </div></div></section></div></main>;
}
export default Settings;
